SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Album](
	[Album_ID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](255) NULL,
	[Release_date] [date] NULL,
	[Artist_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Album] ADD PRIMARY KEY CLUSTERED 
(
	[Album_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Album]  WITH CHECK ADD FOREIGN KEY([Artist_ID])
REFERENCES [dbo].[Artist] ([Artist_ID])
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AlbumSong](
	[Album_ID] [int] NOT NULL,
	[Song_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AlbumSong] ADD PRIMARY KEY CLUSTERED 
(
	[Album_ID] ASC,
	[Song_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AlbumSong]  WITH CHECK ADD FOREIGN KEY([Album_ID])
REFERENCES [dbo].[Album] ([Album_ID])
GO
ALTER TABLE [dbo].[AlbumSong]  WITH CHECK ADD FOREIGN KEY([Song_ID])
REFERENCES [dbo].[Song] ([Song_ID])
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Artist](
	[Artist_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NULL,
	[User_Id] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Artist] ADD PRIMARY KEY CLUSTERED 
(
	[Artist_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Artist]  WITH CHECK ADD  CONSTRAINT [fk_artist_user] FOREIGN KEY([User_Id])
REFERENCES [dbo].[Listener] ([User_ID])
GO
ALTER TABLE [dbo].[Artist] CHECK CONSTRAINT [fk_artist_user]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Listener](
	[User_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NULL,
	[Password] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Listener] ADD PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Moderator](
	[Mod_ID] [int] IDENTITY(1,1) NOT NULL,
	[User_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Moderator] ADD PRIMARY KEY CLUSTERED 
(
	[Mod_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Moderator]  WITH CHECK ADD FOREIGN KEY([User_ID])
REFERENCES [dbo].[Listener] ([User_ID])
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Playlist](
	[Playlist_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Creation_Date] [date] NOT NULL,
	[User_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Playlist] ADD PRIMARY KEY CLUSTERED 
(
	[Playlist_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Playlist]  WITH CHECK ADD FOREIGN KEY([User_ID])
REFERENCES [dbo].[Listener] ([User_ID])
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PlaylistSongs](
	[Playlist_ID] [int] NOT NULL,
	[Song_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlaylistSongs] ADD PRIMARY KEY CLUSTERED 
(
	[Playlist_ID] ASC,
	[Song_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PlaylistSongs]  WITH CHECK ADD FOREIGN KEY([Playlist_ID])
REFERENCES [dbo].[Playlist] ([Playlist_ID])
GO
ALTER TABLE [dbo].[PlaylistSongs]  WITH CHECK ADD FOREIGN KEY([Song_ID])
REFERENCES [dbo].[Song] ([Song_ID])
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Song](
	[Song_ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](255) NULL,
	[Rating] [int] NULL,
	[Duration] [time](7) NULL,
	[Release_date] [date] NULL,
	[Artist_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Song] ADD PRIMARY KEY CLUSTERED 
(
	[Song_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Song]  WITH CHECK ADD FOREIGN KEY([Artist_ID])
REFERENCES [dbo].[Artist] ([Artist_ID])
GO

